version: '3.8'

services:
  customer-backend:
    image: 191481838776.dkr.ecr.ap-south-2.amazonaws.com/hinchmart:latest
    container_name: customer-backend
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT:-9000}
      # Database Configuration
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DDL_AUTO: ${DB_DDL_AUTO:-update}
      SHOW_SQL: ${SHOW_SQL:-false}
      FORMAT_SQL: ${FORMAT_SQL:-false}
      # AWS S3 Storage
      AWS_REGION: ${AWS_REGION:-ap-south-2}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-hinchmart-storage-191481838776-ap-south-2-an}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      # Location & Maps Configuration
      LOCATION_PROVIDER: ${LOCATION_PROVIDER:-google}
      MAPS_API_KEY: ${MAPS_API_KEY:-}
      # Resend Email Configuration
      RESEND_API_URL: ${RESEND_API_URL:-https://api.resend.com/emails}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL:-noreply@hinchmart.com}
      RESEND_FROM_NAME: ${RESEND_FROM_NAME:-HinchMart}
      RESEND_REPLY_TO: ${RESEND_REPLY_TO:-hinchmart@gmail.com}
      # Firebase / JWT Authentication & Authorization Credentials
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL:-}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY:-}

