export const CONSTRUCTION_CATEGORIES = [
  {
    id: 'electrical',
    categoryId: 1,
    name: 'Electrical',
    slug: 'electrical',
    icon: 'Zap',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    description: 'Industrial wires, cables, switchgear, distribution boards, lighting fixtures, and power automation systems.',
    sortOrder: 1,
    active: true,
    subcategories: [
      {
        id: 'sub_1_1',
        subcategoryId: 101,
        categoryId: 1,
        categoryName: 'Electrical',
        name: 'Industrial Wires & Cables',
        slug: 'industrial-wires-cables',
        imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_101', brandId: 101, name: 'Polycab', slug: 'polycab' },
          { id: 'b_102', brandId: 102, name: 'Havells', slug: 'havells' },
          { id: 'b_103', brandId: 103, name: 'Finolex', slug: 'finolex' },
          { id: 'b_104', brandId: 104, name: 'RR Kabel', slug: 'rr-kabel' },
          { id: 'b_105', brandId: 105, name: 'KEI Industries', slug: 'kei-industries' },
        ],
      },
      {
        id: 'sub_1_2',
        subcategoryId: 102,
        categoryId: 1,
        categoryName: 'Electrical',
        name: 'Switchgear & Distribution Boards',
        slug: 'switchgear-distribution-boards',
        imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_106', brandId: 106, name: 'Schneider Electric', slug: 'schneider-electric' },
          { id: 'b_107', brandId: 107, name: 'Legrand', slug: 'legrand' },
          { id: 'b_108', brandId: 108, name: 'L&T Electrical', slug: 'lt-electrical' },
          { id: 'b_109', brandId: 109, name: 'Siemens', slug: 'siemens' },
          { id: 'b_110', brandId: 110, name: 'ABB', slug: 'abb' },
        ],
      },
      {
        id: 'sub_1_3',
        subcategoryId: 103,
        categoryId: 1,
        categoryName: 'Electrical',
        name: 'Lighting & Commercial Fixtures',
        slug: 'lighting-commercial-fixtures',
        imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_111', brandId: 111, name: 'Philips', slug: 'philips' },
          { id: 'b_112', brandId: 112, name: 'Wipro Lighting', slug: 'wipro-lighting' },
          { id: 'b_102', brandId: 102, name: 'Havells', slug: 'havells' },
          { id: 'b_113', brandId: 113, name: 'Syska', slug: 'syska' },
          { id: 'b_114', brandId: 114, name: 'Crompton', slug: 'crompton' },
        ],
      },
      {
        id: 'sub_1_4',
        subcategoryId: 104,
        categoryId: 1,
        categoryName: 'Electrical',
        name: 'Conduits, Trays & Enclosures',
        slug: 'conduits-trays-enclosures',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
        sortOrder: 4,
        active: true,
        eligibleBrands: [
          { id: 'b_115', brandId: 115, name: 'Precision', slug: 'precision' },
          { id: 'b_116', brandId: 116, name: 'AKG', slug: 'akg' },
          { id: 'b_117', brandId: 117, name: 'Supreme', slug: 'supreme' },
          { id: 'b_118', brandId: 118, name: 'VIP', slug: 'vip' },
        ],
      },
    ],
    specFields: [
      { name: 'voltageRating', label: 'Voltage Rating', type: 'select', options: ['1100V (LT)', '11kV (HT)', '33kV (EHT)', '415V 3-Phase', '230V 1-Phase'], required: true },
      { name: 'conductorMaterial', label: 'Conductor Material', type: 'select', options: ['Electrolytic Copper', 'EC Grade Aluminium', 'Copper Clad Aluminium'], required: true },
      { name: 'isStandard', label: 'IS Standard', type: 'select', options: ['IS 694', 'IS 1554 Part 1', 'IS 7098', 'IS 8828', 'IEC 60947'], required: true },
    ],
  },
  {
    id: 'interior',
    categoryId: 2,
    name: 'Interior',
    slug: 'interior',
    icon: 'Layers',
    imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&auto=format&fit=crop&q=80',
    description: 'Internal decorative finishes, interior wall paints, false ceiling systems, vitrified tiles, and architectural laminates.',
    sortOrder: 2,
    active: true,
    subcategories: [
      {
        id: 'sub_2_1',
        subcategoryId: 201,
        categoryId: 2,
        categoryName: 'Interior',
        name: 'Interior Wall Paints & Primers',
        slug: 'interior-wall-paints-primers',
        imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_201', brandId: 201, name: 'Asian Paints', slug: 'asian-paints' },
          { id: 'b_202', brandId: 202, name: 'Berger Paints', slug: 'berger-paints' },
          { id: 'b_203', brandId: 203, name: 'Kansai Nerolac', slug: 'nerolac' },
          { id: 'b_204', brandId: 204, name: 'Dulux', slug: 'dulux' },
          { id: 'b_205', brandId: 205, name: 'Indigo Paints', slug: 'indigo-paints' },
        ],
      },
      {
        id: 'sub_2_2',
        subcategoryId: 202,
        categoryId: 2,
        categoryName: 'Interior',
        name: 'Vitrified Tiles & Marble Slabs',
        slug: 'vitrified-tiles-marble-slabs',
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_206', brandId: 206, name: 'Kajaria', slug: 'kajaria' },
          { id: 'b_207', brandId: 207, name: 'Somany Ceramics', slug: 'somany' },
          { id: 'b_208', brandId: 208, name: 'Nitco', slug: 'nitco' },
          { id: 'b_209', brandId: 209, name: 'Johnson Tiles', slug: 'johnson-tiles' },
          { id: 'b_210', brandId: 210, name: 'RAK Ceramics', slug: 'rak-ceramics' },
        ],
      },
      {
        id: 'sub_2_3',
        subcategoryId: 203,
        categoryId: 2,
        categoryName: 'Interior',
        name: 'False Ceilings & Gypsum Boards',
        slug: 'false-ceilings-gypsum-boards',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_211', brandId: 211, name: 'Saint-Gobain Gyproc', slug: 'saint-gobain-gyproc' },
          { id: 'b_212', brandId: 212, name: 'USG Boral', slug: 'usg-boral' },
          { id: 'b_213', brandId: 213, name: 'Armstrong', slug: 'armstrong' },
          { id: 'b_214', brandId: 214, name: 'Shera', slug: 'shera' },
        ],
      },
      {
        id: 'sub_2_4',
        subcategoryId: 204,
        categoryId: 2,
        categoryName: 'Interior',
        name: 'Laminates, Veneers & Plywood',
        slug: 'laminates-veneers-plywood',
        imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        sortOrder: 4,
        active: true,
        eligibleBrands: [
          { id: 'b_215', brandId: 215, name: 'CenturyPly', slug: 'centuryply' },
          { id: 'b_216', brandId: 216, name: 'Greenlam', slug: 'greenlam' },
          { id: 'b_217', brandId: 217, name: 'Greenply', slug: 'greenply' },
          { id: 'b_218', brandId: 218, name: 'Merino', slug: 'merino' },
          { id: 'b_219', brandId: 219, name: 'Royale Touche', slug: 'royale-touche' },
        ],
      },
    ],
    specFields: [
      { name: 'finishType', label: 'Finish Type', type: 'select', options: ['Matte', 'Glossy', 'High Gloss', 'Satin', 'Textured', 'Rustic'], required: true },
      { name: 'coverageArea', label: 'Coverage Area', type: 'text', placeholder: 'e.g. 120-140 sq.ft/Litre', required: false },
    ],
  },
  {
    id: 'exterior',
    categoryId: 3,
    name: 'Exterior',
    slug: 'exterior',
    icon: 'Building2',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
    description: 'Weatherproof exterior coatings, structural ACP cladding, industrial roofing sheets, and outdoor civil pavers.',
    sortOrder: 3,
    active: true,
    subcategories: [
      {
        id: 'sub_3_1',
        subcategoryId: 301,
        categoryId: 3,
        categoryName: 'Exterior',
        name: 'Exterior Weatherproof Coatings',
        slug: 'exterior-weatherproof-coatings',
        imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_201', brandId: 201, name: 'Asian Paints (Apex Ultima)', slug: 'asian-paints' },
          { id: 'b_202', brandId: 202, name: 'Berger (WeatherCoat)', slug: 'berger-paints' },
          { id: 'b_203', brandId: 203, name: 'Nerolac (Excel)', slug: 'nerolac' },
          { id: 'b_301', brandId: 301, name: 'Dr. Fixit', slug: 'dr-fixit' },
        ],
      },
      {
        id: 'sub_3_2',
        subcategoryId: 302,
        categoryId: 3,
        categoryName: 'Exterior',
        name: 'Roofing Sheets & Color Coated Profile',
        slug: 'roofing-sheets-color-coated-profile',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_302', brandId: 302, name: 'Tata BlueScope Steel', slug: 'tata-bluescope' },
          { id: 'b_303', brandId: 303, name: 'JSW Colouron+', slug: 'jsw-colouron' },
          { id: 'b_304', brandId: 304, name: 'Jindal Sabrang', slug: 'jindal-sabrang' },
          { id: 'b_305', brandId: 305, name: 'Everlast (HIL)', slug: 'everlast' },
        ],
      },
      {
        id: 'sub_3_3',
        subcategoryId: 303,
        categoryId: 3,
        categoryName: 'Exterior',
        name: 'ACP Panels & Architectural Cladding',
        slug: 'acp-panels-architectural-cladding',
        imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_306', brandId: 306, name: 'Aludecor', slug: 'aludecor' },
          { id: 'b_307', brandId: 307, name: 'Alstone', slug: 'alstone' },
          { id: 'b_308', brandId: 308, name: 'Eurobond', slug: 'eurobond' },
          { id: 'b_309', brandId: 309, name: 'Fundermax', slug: 'fundermax' },
        ],
      },
      {
        id: 'sub_3_4',
        subcategoryId: 304,
        categoryId: 3,
        categoryName: 'Exterior',
        name: 'Paver Blocks & Heavy Kerbs',
        slug: 'paver-blocks-heavy-kerbs',
        imageUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=800&auto=format&fit=crop&q=80',
        sortOrder: 4,
        active: true,
        eligibleBrands: [
          { id: 'b_310', brandId: 310, name: 'UltraTech Pavers', slug: 'ultratech-pavers' },
          { id: 'b_311', brandId: 311, name: 'Vyara Tiles', slug: 'vyara-tiles' },
          { id: 'b_312', brandId: 312, name: 'Basant Betons', slug: 'basant-betons' },
        ],
      },
    ],
    specFields: [
      { name: 'thickness', label: 'Thickness / Gauge', type: 'text', placeholder: 'e.g. 0.50mm / 4mm ACP', required: true },
      { name: 'warrantyYears', label: 'Weather Warranty', type: 'select', options: ['5 Years', '10 Years', '15 Years', '20 Years'], required: false },
    ],
  },
  {
    id: 'furniture',
    categoryId: 4,
    name: 'Furniture',
    slug: 'furniture',
    icon: 'Package',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Commercial workstations, modular office setups, heavy industrial pallet storage racks, and ergonomic seating.',
    sortOrder: 4,
    active: true,
    subcategories: [
      {
        id: 'sub_4_1',
        subcategoryId: 401,
        categoryId: 4,
        categoryName: 'Furniture',
        name: 'Commercial Office Desks & Modular Workstations',
        slug: 'commercial-office-desks-modular-workstations',
        imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_401', brandId: 401, name: 'Godrej Interio', slug: 'godrej-interio' },
          { id: 'b_402', brandId: 402, name: 'Featherlite', slug: 'featherlite' },
          { id: 'b_403', brandId: 403, name: 'Nilkamal', slug: 'nilkamal' },
          { id: 'b_404', brandId: 404, name: 'Durian', slug: 'durian' },
          { id: 'b_405', brandId: 405, name: 'Spacewood', slug: 'spacewood' },
        ],
      },
      {
        id: 'sub_4_2',
        subcategoryId: 402,
        categoryId: 4,
        categoryName: 'Furniture',
        name: 'Industrial Heavy Duty Storage & Pallet Racks',
        slug: 'industrial-heavy-duty-storage-pallet-racks',
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_406', brandId: 406, name: 'Godrej Storage Solutions', slug: 'godrej-storage' },
          { id: 'b_407', brandId: 407, name: 'Kompress', slug: 'kompress' },
          { id: 'b_408', brandId: 408, name: 'Nilkamal Material Handling', slug: 'nilkamal-mh' },
          { id: 'b_409', brandId: 409, name: 'Mex Storage Systems', slug: 'mex-storage' },
        ],
      },
      {
        id: 'sub_4_3',
        subcategoryId: 403,
        categoryId: 4,
        categoryName: 'Furniture',
        name: 'Ergonomic Executive & Conference Chairs',
        slug: 'ergonomic-executive-conference-chairs',
        imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_402', brandId: 402, name: 'Featherlite', slug: 'featherlite' },
          { id: 'b_401', brandId: 401, name: 'Godrej Interio', slug: 'godrej-interio' },
          { id: 'b_410', brandId: 410, name: 'Steelcase', slug: 'steelcase' },
          { id: 'b_411', brandId: 411, name: 'Herman Miller', slug: 'herman-miller' },
        ],
      },
    ],
    specFields: [
      { name: 'material', label: 'Primary Construction Material', type: 'select', options: ['CRCA High-Grade Steel', 'BWP Hardwood Plywood', 'Commercial Particle Board', 'Tempered Glass & Steel'], required: true },
      { name: 'loadCapacity', label: 'Load Capacity', type: 'text', placeholder: 'e.g. 500 kg per shelf level', required: false },
    ],
  },
  {
    id: 'plumbing',
    categoryId: 5,
    name: 'Plumbing',
    slug: 'plumbing',
    icon: 'Package',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    description: 'CPVC, UPVC, and SWR piping networks, industrial water pumps, institutional sanitaryware, and bath fittings.',
    sortOrder: 5,
    active: true,
    subcategories: [
      {
        id: 'sub_5_1',
        subcategoryId: 501,
        categoryId: 5,
        categoryName: 'Plumbing',
        name: 'CPVC & UPVC High-Pressure Pipes',
        slug: 'cpvc-upvc-high-pressure-pipes',
        imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_501', brandId: 501, name: 'Astral Pipes', slug: 'astral' },
          { id: 'b_502', brandId: 502, name: 'Supreme Industries', slug: 'supreme' },
          { id: 'b_503', brandId: 503, name: 'Ashirvad Pipes', slug: 'ashirvad' },
          { id: 'b_103', brandId: 103, name: 'Finolex Pipes', slug: 'finolex' },
          { id: 'b_504', brandId: 504, name: 'Prince Pipes', slug: 'prince-pipes' },
        ],
      },
      {
        id: 'sub_5_2',
        subcategoryId: 502,
        categoryId: 5,
        categoryName: 'Plumbing',
        name: 'Sanitaryware & Ceramic Basins',
        slug: 'sanitaryware-ceramic-basins',
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_505', brandId: 505, name: 'Jaquar', slug: 'jaquar' },
          { id: 'b_506', brandId: 506, name: 'Hindware', slug: 'hindware' },
          { id: 'b_507', brandId: 507, name: 'Cera', slug: 'cera' },
          { id: 'b_508', brandId: 508, name: 'Kohler', slug: 'kohler' },
          { id: 'b_509', brandId: 509, name: 'Parryware', slug: 'parryware' },
        ],
      },
      {
        id: 'sub_5_3',
        subcategoryId: 503,
        categoryId: 5,
        categoryName: 'Plumbing',
        name: 'Water Storage Tanks & Loft Reservoirs',
        slug: 'water-storage-tanks-loft-reservoirs',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_510', brandId: 510, name: 'Sintex', slug: 'sintex' },
          { id: 'b_502', brandId: 502, name: 'Supreme', slug: 'supreme' },
          { id: 'b_511', brandId: 511, name: 'Vectus', slug: 'vectus' },
          { id: 'b_512', brandId: 512, name: 'Plasto', slug: 'plasto' },
        ],
      },
      {
        id: 'sub_5_4',
        subcategoryId: 504,
        categoryId: 5,
        categoryName: 'Plumbing',
        name: 'Industrial Water Pumps & Booster Motors',
        slug: 'industrial-water-pumps-booster-motors',
        imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80',
        sortOrder: 4,
        active: true,
        eligibleBrands: [
          { id: 'b_513', brandId: 513, name: 'Kirloskar Brothers', slug: 'kirloskar' },
          { id: 'b_114', brandId: 114, name: 'Crompton', slug: 'crompton' },
          { id: 'b_514', brandId: 514, name: 'Grundfos', slug: 'grundfos' },
          { id: 'b_515', brandId: 515, name: 'Texmo', slug: 'texmo' },
          { id: 'b_516', brandId: 516, name: 'CRI Pumps', slug: 'cri-pumps' },
        ],
      },
    ],
    specFields: [
      { name: 'pipeClass', label: 'Pressure Rating / Class', type: 'select', options: ['SDR 11 (Class 1)', 'SDR 13.5 (Class 2)', 'SCH 40', 'SCH 80', 'Type A (SWR)', 'Type B (SWR)'], required: true },
      { name: 'diameterSize', label: 'Nominal Diameter', type: 'text', placeholder: 'e.g. 25mm (1 inch) / 110mm', required: true },
      { name: 'isStandard', label: 'IS Standard Certification', type: 'select', options: ['IS 15778 (CPVC)', 'IS 4985 (UPVC)', 'IS 13592 (SWR)', 'IS 1239 (GI)'], required: true },
    ],
  },
  {
    id: 'home-decor',
    categoryId: 6,
    name: 'Home Decor',
    slug: 'home-decor',
    icon: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    description: 'Architectural mirrors, glass facades, designer draperies, decorative wall accents, and interior chandeliers.',
    sortOrder: 6,
    active: true,
    subcategories: [
      {
        id: 'sub_6_1',
        subcategoryId: 601,
        categoryId: 6,
        categoryName: 'Home Decor',
        name: 'Architectural Mirrors & Glass Panels',
        slug: 'architectural-mirrors-glass-panels',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_601', brandId: 601, name: 'Saint-Gobain Glass', slug: 'saint-gobain-glass' },
          { id: 'b_602', brandId: 602, name: 'AIS Glass (Asahi)', slug: 'ais-glass' },
          { id: 'b_603', brandId: 603, name: 'Modiguard', slug: 'modiguard' },
        ],
      },
      {
        id: 'sub_6_2',
        subcategoryId: 602,
        categoryId: 6,
        categoryName: 'Home Decor',
        name: 'Curtains, Blinds & Acoustic Drapery',
        slug: 'curtains-blinds-acoustic-drapery',
        imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_604', brandId: 604, name: "D'Decor", slug: 'ddecor' },
          { id: 'b_605', brandId: 605, name: 'Hunter Douglas', slug: 'hunter-douglas' },
          { id: 'b_606', brandId: 606, name: 'Marvel Blinds', slug: 'marvel-blinds' },
        ],
      },
      {
        id: 'sub_6_3',
        subcategoryId: 603,
        categoryId: 6,
        categoryName: 'Home Decor',
        name: 'Designer Lighting & Modern Chandeliers',
        slug: 'designer-lighting-modern-chandeliers',
        imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_607', brandId: 607, name: 'Tisva', slug: 'tisva' },
          { id: 'b_608', brandId: 608, name: 'Fos Lighting', slug: 'fos-lighting' },
          { id: 'b_609', brandId: 609, name: 'Kapoor Lights', slug: 'kapoor-lights' },
        ],
      },
    ],
    specFields: [
      { name: 'style', label: 'Design Style', type: 'select', options: ['Contemporary', 'Minimalist', 'Industrial Loft', 'Classic Luxury'], required: false },
    ],
  },
  {
    id: 'civil',
    categoryId: 7,
    name: 'Civil',
    slug: 'civil',
    icon: 'Building2',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    description: 'Primary structural steel, TMT rebars, cement, ready mix concrete, AAC blocks, red bricks, and aggregate bulk supplies.',
    sortOrder: 7,
    active: true,
    subcategories: [
      {
        id: 'sub_7_1',
        subcategoryId: 701,
        categoryId: 7,
        categoryName: 'Civil',
        name: 'TMT Steel Rebars & Structural Sections',
        slug: 'tmt-steel-rebars-structural-sections',
        imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_701', brandId: 701, name: 'Tata Tiscon', slug: 'tata-tiscon' },
          { id: 'b_702', brandId: 702, name: 'JSW Neosteel', slug: 'jsw-neosteel' },
          { id: 'b_703', brandId: 703, name: 'Jindal Panther', slug: 'jindal-panther' },
          { id: 'b_704', brandId: 704, name: 'SAIL Steel', slug: 'sail-steel' },
          { id: 'b_705', brandId: 705, name: 'Kamdhenu Nxt', slug: 'kamdhenu' },
          { id: 'b_706', brandId: 706, name: 'Vizag Steel (RINL)', slug: 'vizag-steel' },
        ],
      },
      {
        id: 'sub_7_2',
        subcategoryId: 702,
        categoryId: 7,
        categoryName: 'Civil',
        name: 'Cement, Ready Mix Concrete (RMC) & Clinker',
        slug: 'cement-ready-mix-concrete-clinker',
        imageUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_707', brandId: 707, name: 'UltraTech Cement', slug: 'ultratech' },
          { id: 'b_708', brandId: 708, name: 'Ambuja Cement', slug: 'ambuja' },
          { id: 'b_709', brandId: 709, name: 'ACC Limited', slug: 'acc' },
          { id: 'b_710', brandId: 710, name: 'Shree Cement', slug: 'shree-cement' },
          { id: 'b_711', brandId: 711, name: 'Dalmia Bharat', slug: 'dalmia-bharat' },
        ],
      },
      {
        id: 'sub_7_3',
        subcategoryId: 703,
        categoryId: 7,
        categoryName: 'Civil',
        name: 'AAC Blocks, Red Clay Bricks & Solid Pavers',
        slug: 'aac-blocks-red-clay-bricks-solid-pavers',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_712', brandId: 712, name: 'Birla Aerocon', slug: 'birla-aerocon' },
          { id: 'b_713', brandId: 713, name: 'Magicrete', slug: 'magicrete' },
          { id: 'b_714', brandId: 714, name: 'Siporex', slug: 'siporex' },
          { id: 'b_715', brandId: 715, name: 'Godrej AAC', slug: 'godrej-aac' },
        ],
      },
      {
        id: 'sub_7_4',
        subcategoryId: 704,
        categoryId: 7,
        categoryName: 'Civil',
        name: 'Tile Adhesives, Grouts & Ready-Mix Plaster',
        slug: 'tile-adhesives-grouts-ready-mix-plaster',
        imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        sortOrder: 4,
        active: true,
        eligibleBrands: [
          { id: 'b_716', brandId: 716, name: 'Roff (Pidilite)', slug: 'roff' },
          { id: 'b_717', brandId: 717, name: 'UltraTech Tilefixo', slug: 'ultratech-tilefixo' },
          { id: 'b_301', brandId: 301, name: 'Dr. Fixit', slug: 'dr-fixit' },
          { id: 'b_718', brandId: 718, name: 'Weber Saint-Gobain', slug: 'weber' },
          { id: 'b_719', brandId: 719, name: 'Bostik', slug: 'bostik' },
        ],
      },
    ],
    specFields: [
      { name: 'steelGrade', label: 'Steel / Cement Grade', type: 'select', options: ['Fe 550D (High Ductility)', 'Fe 500D', 'Fe 600', 'OPC 53 Grade', 'OPC 43 Grade', 'PPC Super', 'M25 Concrete', 'M30 Concrete'], required: true },
      { name: 'bisStandard', label: 'BIS Standard Certification', type: 'select', options: ['IS 1786:2008 (TMT)', 'IS 269:2015 (Cement)', 'IS 2185 (AAC)', 'IS 1077 (Clay Bricks)'], required: true },
      { name: 'diameterSize', label: 'Standard Bar Diameter', type: 'select', options: ['8 mm', '10 mm', '12 mm', '16 mm', '20 mm', '25 mm', '32 mm', 'NA (Bulk/Cement)'], required: false },
    ],
  },
  {
    id: 'hardware',
    categoryId: 8,
    name: 'Hardware',
    slug: 'hardware',
    icon: 'Package',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80',
    description: 'High-tensile industrial fasteners, power tools, commercial door hardware, welding systems, and construction safety PPE.',
    sortOrder: 8,
    active: true,
    subcategories: [
      {
        id: 'sub_8_1',
        subcategoryId: 801,
        categoryId: 8,
        categoryName: 'Hardware',
        name: 'Industrial Fasteners, High-Tensile Bolts & Anchors',
        slug: 'industrial-fasteners-high-tensile-bolts-anchors',
        imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80',
        sortOrder: 1,
        active: true,
        eligibleBrands: [
          { id: 'b_801', brandId: 801, name: 'Unbrako', slug: 'unbrako' },
          { id: 'b_802', brandId: 802, name: 'Sundram Fasteners (TVS)', slug: 'sundram-fasteners' },
          { id: 'b_803', brandId: 803, name: 'Hilti', slug: 'hilti' },
          { id: 'b_804', brandId: 804, name: 'Fischer India', slug: 'fischer' },
        ],
      },
      {
        id: 'sub_8_2',
        subcategoryId: 802,
        categoryId: 8,
        categoryName: 'Hardware',
        name: 'Heavy Power Tools, Cutters & Impact Drills',
        slug: 'heavy-power-tools-cutters-impact-drills',
        imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80',
        sortOrder: 2,
        active: true,
        eligibleBrands: [
          { id: 'b_805', brandId: 805, name: 'Bosch Professional', slug: 'bosch' },
          { id: 'b_806', brandId: 806, name: 'DeWalt', slug: 'dewalt' },
          { id: 'b_807', brandId: 807, name: 'Makita', slug: 'makita' },
          { id: 'b_808', brandId: 808, name: 'Stanley', slug: 'stanley' },
          { id: 'b_809', brandId: 809, name: 'Hilti Power Tools', slug: 'hilti-tools' },
        ],
      },
      {
        id: 'sub_8_3',
        subcategoryId: 803,
        categoryId: 8,
        categoryName: 'Hardware',
        name: 'Door Locks, Architectural Hinges & Heavy Fittings',
        slug: 'door-locks-architectural-hinges-heavy-fittings',
        imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        sortOrder: 3,
        active: true,
        eligibleBrands: [
          { id: 'b_810', brandId: 810, name: 'Godrej Locks', slug: 'godrej-locks' },
          { id: 'b_811', brandId: 811, name: 'Yale', slug: 'yale' },
          { id: 'b_812', brandId: 812, name: 'Dorma', slug: 'dorma' },
          { id: 'b_813', brandId: 813, name: 'Hafele', slug: 'hafele' },
          { id: 'b_814', brandId: 814, name: 'Ozone', slug: 'ozone' },
        ],
      },
      {
        id: 'sub_8_4',
        subcategoryId: 804,
        categoryId: 8,
        categoryName: 'Hardware',
        name: 'Construction Safety Equipment & Certified PPE',
        slug: 'construction-safety-equipment-certified-ppe',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
        sortOrder: 4,
        active: true,
        eligibleBrands: [
          { id: 'b_815', brandId: 815, name: 'Karam Safety', slug: 'karam' },
          { id: 'b_816', brandId: 816, name: '3M Safety', slug: '3m' },
          { id: 'b_817', brandId: 817, name: 'Honeywell', slug: 'honeywell' },
          { id: 'b_818', brandId: 818, name: 'Allen Cooper', slug: 'allen-cooper' },
          { id: 'b_819', brandId: 819, name: 'Udyogi', slug: 'udyogi' },
        ],
      },
    ],
    specFields: [
      { name: 'gradeClass', label: 'Material Grade / Class', type: 'select', options: ['Grade 8.8 High Tensile', 'Grade 10.9', 'Stainless Steel SS304', 'SS316 Marine Grade', 'Drop Forged Carbon Steel'], required: true },
      { name: 'powerRating', label: 'Power Input / Tool Wattage', type: 'text', placeholder: 'e.g. 850W / 20V Cordless Li-Ion', required: false },
    ],
  },
];
