export const BUSINESS_TYPES = [
  'MANUFACTURER',
  'DISTRIBUTOR',
  'WHOLESALER',
  'RETAILER',
  'DEALER',
  'CONTRACTOR_FABRICATOR',
  'OTHER',
];

export const ONBOARDING_STATUS = {
  STEP_1: 'STEP_1',
  STEP_2: 'STEP_2',
  STEP_3: 'STEP_3',
  PENDING_REVIEW: 'PENDING_REVIEW',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  NOT_UPLOADED: 'NOT_UPLOADED',
};

export const DOCUMENT_TYPES = [
  'PAN',
  'AADHAAR',
  'GST',
  'CHEQUE',
  'TRADE_LICENSE',
  'OTHER',
];
