#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Aug 29 15:11:48 IST 2026
prefixes-plexus.snapshots.txt.error=
prefixes-plexus.snapshots.txt.lastUpdated=1787996469774
prefixes-central.txt.lastUpdated=1787996463380
prefixes-oss.snapshots.txt.lastUpdated=1787996488484
prefixes-sonatype-nexus-snapshots.txt.error=
prefixes-jboss-public-repository-group.txt.lastUpdated=1787996472692
prefixes-jboss-public-repository-group.txt.error=
prefixes-ow2-snapshot.txt.lastUpdated=1787996508261
prefixes-sonatype-nexus-snapshots.txt.lastUpdated=1787996465923
prefixes-apache.snapshots.txt.lastUpdated=1787996471462
prefixes-oss.snapshots.txt.error=
